package com.example.tricolv2sb.Entity.Enum;

public enum ActionName {
    CREATE,
    UPDATE,
    READ,
    DELETE,
    RECEIVE,
    VALIDATE,
    CANCEL,
    GOODSISSUE_CREATED,
    GOODSISSUE_DELETED,
    GOODSISSUE_VALIDATED,
    GOODSISSUE_CANCELED,
    ORDER_CREATED,
    ORDER_VALIDATED,
    ORDER_CANCELLED,
    ORDER_RECEIVED,
    ROLE_ASSIGNED,
    PERMISSION_ASSIGNED
}
